#!/usr/bin/env bun
import { randomBytes } from "node:crypto";
import { chmodSync } from "node:fs";

// Generates the secrets + connection URLs the platform-neutral stack (docker-compose.prod.yml) needs,
// for Tier B/D onboarding (Portainer / EasyPanel / plain VM) where there is no Coolify to mint magic
// vars. Writes a .env holding the TWO database roles (superuser + NON-superuser runtime), JWT_SECRET,
// ENCRYPTION_KEY, and the derived MIGRATION_DATABASE_URL / DATABASE_URL / LANGGRAPH_DATABASE_URL /
// PUBLIC_URL. For these tiers the .env IS the deploy destination for the secrets (Coolify keeps its
// own store and ignores this script). See docs/deploy.md for the two-role contract.

export interface OnboardingEnvOptions {
  publicUrl: string;
  dbHost?: string;
  dbPort?: number;
  dbName?: string;
  pgUser?: string;
  appUser?: string;
  corsOrigin?: string;
  appPort?: string;
  // Bare hostname Caddy serves TLS for (docker-compose.portainer.yml). Defaults to PUBLIC_URL's host.
  caddyDomain?: string;
  // Optional ACME contact for expiry notices + better rate-limit standing. Caddy works without it.
  acmeEmail?: string;
}

export interface OnboardingEnv {
  PUBLIC_URL: string;
  CORS_ORIGIN: string;
  LOG_LEVEL: string;
  APP_PORT: string;
  // NOTE: disabled ONLY for this trusted first-run deploy (the operator drives /setup right after
  // provisioning), removing token friction. The app-wide default in src/config.ts stays `true`.
  SETUP_TOKEN_REQUIRED: string;
  DATABASE_NAME: string;
  POSTGRES_USER: string;
  POSTGRES_PASSWORD: string;
  JWT_SECRET: string;
  ENCRYPTION_KEY: string;
  MIGRATION_DATABASE_URL: string;
  DATABASE_URL: string;
  LANGGRAPH_DATABASE_URL: string;
  // Consumed only by docker-compose.portainer.yml's bundled Caddy; harmless for the BYO-proxy stack.
  CADDY_DOMAIN: string;
  ACME_EMAIL?: string;
}

// URL-safe secret: hex has no characters that need escaping inside a postgres:// URL or a .env value.
function secret(bytes: number): string {
  return randomBytes(bytes).toString("hex");
}

const ROLE_NAME = /^[A-Za-z0-9_-]+$/;

export function buildOnboardingEnv(opts: OnboardingEnvOptions): OnboardingEnv {
  const publicUrl = opts.publicUrl.replace(/\/+$/, "");
  if (!/^https?:\/\//.test(publicUrl)) {
    throw new Error(
      `PUBLIC_URL must start with http:// or https:// (got "${opts.publicUrl}")`,
    );
  }
  const dbHost = opts.dbHost ?? "postgres";
  const dbPort = opts.dbPort ?? 5432;
  const dbName = opts.dbName ?? "fazerai_agents_db";
  const pgUser = opts.pgUser ?? "postgres";
  const appUser = opts.appUser ?? "fazerai_app";
  // db-bootstrap.ts interpolates the runtime role name into DDL as a quoted identifier; keep both
  // role names to the safe charset it accepts so a generated .env can never break that out.
  for (const [label, name] of [
    ["postgres superuser", pgUser],
    ["app role", appUser],
  ] as const) {
    if (!ROLE_NAME.test(name)) {
      throw new Error(
        `${label} name must match [A-Za-z0-9_-]+ (got "${name}")`,
      );
    }
  }

  const pgPassword = secret(24);
  const appPassword = secret(24);
  const authority = (user: string, pass: string) =>
    `postgres://${user}:${pass}@${dbHost}:${dbPort}/${dbName}`;
  // The checkpointer pool MUST be the runtime (non-superuser) role, never the migration URL.
  const databaseUrl = authority(appUser, appPassword);

  // Caddy serves TLS for the bare host; PUBLIC_URL carries the scheme so derive the host from it.
  const caddyDomain = opts.caddyDomain ?? new URL(publicUrl).hostname;
  const acmeEmail = opts.acmeEmail?.trim();
  if (acmeEmail !== undefined && acmeEmail !== "" && !acmeEmail.includes("@")) {
    throw new Error(`ACME_EMAIL must be an email address (got "${acmeEmail}")`);
  }

  return {
    PUBLIC_URL: publicUrl,
    // Default to the public URL, NOT `*`: the WS realtime origin check does an exact match, so a
    // literal `*` matches no real Origin and 403s every WebSocket upgrade. origin.ts strips the
    // scheme, so the full URL works as the allowlist entry.
    CORS_ORIGIN: opts.corsOrigin ?? publicUrl,
    LOG_LEVEL: "info",
    APP_PORT: opts.appPort ?? "3000",
    SETUP_TOKEN_REQUIRED: "false",
    DATABASE_NAME: dbName,
    POSTGRES_USER: pgUser,
    POSTGRES_PASSWORD: pgPassword,
    JWT_SECRET: secret(32),
    ENCRYPTION_KEY: secret(32),
    MIGRATION_DATABASE_URL: authority(pgUser, pgPassword),
    DATABASE_URL: databaseUrl,
    LANGGRAPH_DATABASE_URL: databaseUrl,
    CADDY_DOMAIN: caddyDomain,
    ...(acmeEmail ? { ACME_EMAIL: acmeEmail } : {}),
  };
}

function serializeEnv(env: OnboardingEnv): string {
  const header = [
    "# Generated by scripts/gen-onboarding-env.ts for docker-compose.prod.yml.",
    "# SENSITIVE: holds DB passwords, JWT_SECRET and ENCRYPTION_KEY. Do NOT commit.",
    "# Rotating ENCRYPTION_KEY invalidates all encrypted-at-rest data (vault, Chatwoot tokens).",
    "",
    "",
  ].join("\n");
  return `${header}${Object.entries(env)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n")}\n`;
}

function flag(name: string): string | undefined {
  const eq = `--${name}=`;
  const hit = process.argv.find((a) => a.startsWith(eq));
  if (hit) return hit.slice(eq.length);
  const idx = process.argv.indexOf(`--${name}`);
  const next = process.argv[idx + 1];
  if (idx !== -1 && next && !next.startsWith("--")) return next;
  return undefined;
}

async function main() {
  const publicUrl = flag("public-url") ?? process.env.PUBLIC_URL;
  if (!publicUrl) {
    console.error(
      "usage: bun scripts/gen-onboarding-env.ts --public-url https://agents.example.com [--out .env] [--force]\n" +
        "       [--db-host postgres] [--db-port 5432] [--db-name fazerai_agents_db] [--pg-user postgres] [--app-user fazerai_app]\n" +
        "       [--caddy-domain agents.example.com] [--acme-email you@example.com]  # for docker-compose.portainer.yml",
    );
    process.exit(1);
  }
  const out = flag("out") ?? ".env";
  const force = process.argv.includes("--force");
  if (!force && (await Bun.file(out).exists())) {
    console.error(
      `refusing to overwrite existing ${out} (would rotate secrets and break a running deploy). Pass --force to replace.`,
    );
    process.exit(1);
  }

  const env = buildOnboardingEnv({
    publicUrl,
    dbHost: flag("db-host"),
    dbPort: flag("db-port") ? Number(flag("db-port")) : undefined,
    dbName: flag("db-name"),
    pgUser: flag("pg-user"),
    appUser: flag("app-user"),
    corsOrigin: flag("cors-origin"),
    appPort: flag("app-port"),
    caddyDomain: flag("caddy-domain"),
    acmeEmail: flag("acme-email"),
  });

  await Bun.write(out, serializeEnv(env));
  try {
    chmodSync(out, 0o600);
  } catch {
    // best-effort (e.g. a non-POSIX filesystem); the file is written regardless.
  }

  // Masked summary — never print the secret values (they would land in logs).
  const appRole = new URL(env.DATABASE_URL).username;
  console.log(
    `wrote ${out} (chmod 600): PUBLIC_URL=${env.PUBLIC_URL}, db=${env.DATABASE_NAME}, superuser=${env.POSTGRES_USER}, runtime role=${appRole} (non-superuser).`,
  );
  console.log(
    "Secrets (POSTGRES_PASSWORD, app-role password, JWT_SECRET, ENCRYPTION_KEY) were written to the file, not printed.",
  );
}

if (import.meta.main) {
  await main();
}
